package greendao;


import com.atguigu.bilibili.modle.faxian.mall.bean.ShopInfo;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shopInfoDaoConfig;

    private final ShopInfoDao shopInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shopInfoDaoConfig = daoConfigMap.get(ShopInfoDao.class).clone();
        shopInfoDaoConfig.initIdentityScope(type);

        shopInfoDao = new ShopInfoDao(shopInfoDaoConfig, this);

        registerDao(ShopInfo.class, shopInfoDao);
    }
    
    public void clear() {
        shopInfoDaoConfig.getIdentityScope().clear();
    }

    public ShopInfoDao getShopInfoDao() {
        return shopInfoDao;
    }

}
